//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gerçek_Zamanlı_Sistemler
{
    using System;
    using System.Collections.Generic;
    
    public partial class OLCUM
    {
        public int ID { get; set; }
        public string MESAFE { get; set; }
        public string DERECE { get; set; }
        public System.DateTime TARIH { get; set; }
    }
}
